name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    environment: catch-mind-ai
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 의존성 설치
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Set up temporary disk space
        run: df -h && sudo mount -t tmpfs -o size=10G tmpfs /mnt && df -h


      - name: 빌드 하고 푸시
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          APP: ${{ secrets.DOCKER_APP_NAME }}
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: $USER/$APP
          tags: latest
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: 배포
        uses: appleboy/ssh-action@master
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          APP: ${{ secrets.DOCKER_APP_NAME }}
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          envs: USER, APP
          # 도커 작업
          script: |
            sudo docker pull $USER/$APP:latest
            sudo docker stop $APP
            sudo docker rm $APP
            sudo docker run -d --name $APP -p 8080:8080 $USER/$APP:latest
            sudo docker container prune -f