name: CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  CI:
    environment: catch-mind-ai
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: 의존성 설치
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: 빌드 권한 설정
        run: chmod +x ./docker-entrypoint.sh

      - name: 도커 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 도커 이미지 생성 및 오리진에 푸시
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          APP: ${{ secrets.DOCKER_APP_NAME }}
        run: |
          docker build -t $USER/$APP -f ./Dockerfile .
          docker push $USER/$APP:latest
  CD:
    runs-on: ubuntu-latest
    needs: CI
    steps:
      - name: 배포
        uses: appleboy/ssh-action@master
        env:
          USER: ${{ secrets.DOCKER_USERNAME }}
          APP: ${{ secrets.DOCKER_APP_NAME }}
        with:
          host: ${{ secrets.HOST }} # EC2 인스턴스 퍼블릭 DNS
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }} # pem 키
          envs: USER, APP
          # 도커 작업
          script: |
            sudo docker pull $USER/$APP:latest
            sudo docker stop $APP
            sudo docker rm $APP
            sudo docker run -d --name $APP -p 8080:8080 $USER/$APP:latest
            sudo docker container prune -f